timeout: 1800s
steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --destination=asia.gcr.io/$PROJECT_ID/circlepod-doc-web:$REVISION_ID
  - --cache=true
  - --cache-ttl=1h
  id: 'push-gcr'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'circlepod-doc-web-services', '--image', 'asia.gcr.io/$PROJECT_ID/circlepod-doc-web:$REVISION_ID', '--region', 'asia-east1', '--platform', 'managed', '--memory', '256Mi', '--set-env-vars', 'NODE_ENV=production,HOST=0.0.0.0', '--allow-unauthenticated']
options:
  machineType: 'E2_HIGHCPU_32'