timeout: 1800s
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia.gcr.io/$PROJECT_ID/circlepod-doc-web:$TAG_NAME', '.']
  id: 'build-gcr'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia.gcr.io/$PROJECT_ID/circlepod-doc-web:$TAG_NAME']
  id: 'push-gcr'
  waitFor:
  - 'build-gcr'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'circlepod-doc-web-services', '--image', 'asia.gcr.io/$PROJECT_ID/circlepod-doc-web:$TAG_NAME', '--region', 'asia-east1', '--platform', 'managed', '--memory', '512Mi', '--set-env-vars', 'NODE_ENV=production,HOST=0.0.0.0', '--allow-unauthenticated']
